version: '3.7'

services:
  jenkins:
    image: jenkins
    ports:
      -'8080:8080'
    container_name: jenkins-server
    version: 1.0
    volumes:
      - /var/local/jenkins
    depends_on:
      - jenkins

  sonarqube:
    image: sonarqube
    ports:
      -'9000:9000'
    container_name: sonarqube-server
    volumes:
      - /var/local/sonarqube
    version: 1.0
